/* Verified incident records are stored locally after a manager checks the source. */
(function () {
  const beachNames=['해운대','광안리','송정','다대포','송도','일광','임랑'];
  const causes=['이안류·높은 파도','음주·무리한 입수','안전구역 이탈','해파리·해양생물 접촉','기타'];
  const load=()=>{try{return JSON.parse(localStorage.getItem('verifiedBeachIncidents')||'[]')}catch(_){return[]}};
  const save=records=>localStorage.setItem('verifiedBeachIncidents',JSON.stringify(records));
  const recent=beach=>{const limit=new Date();limit.setDate(limit.getDate()-30);return load().filter(record=>record.beach===beach&&new Date(record.date)>=limit).sort((a,b)=>b.date.localeCompare(a.date));};
  const baseRender=window.render;
  window.render=function(){baseRender();renderIncidents();addManagerButton();};
  function renderIncidents(){
    const records=recent(beachNames[state.beach]); const card=document.querySelector('.accident'); if(!card)return;
    const groups=causes.map(cause=>({cause,records:records.filter(record=>record.cause===cause)})).filter(group=>group.records.length);
    card.innerHTML=`<div class="acc-top"><b>공식 확인 사고 기록 · 최근 30일</b><span class="count">${records.length}건</span></div>${groups.length?groups.map(group=>`<div class="reason" onclick="showIncidentDetail('${group.cause}')"><i class="dot"></i><span>${group.cause}</span><b>${group.records.length}건</b><i class="chev">›</i></div>`).join(''):'<div class="empty-incidents">등록된 공식 확인 사고 기록이 없습니다.</div>'}`;
    document.querySelector('.incident-data-note')?.remove();
    const note=document.createElement('p');note.className='incident-data-note';note.textContent='관리자가 공식 기관 자료를 확인한 뒤 직접 등록한 기록입니다.';card.insertAdjacentElement('afterend',note);
  }
  window.showIncidentDetail=function(cause){const records=recent(beachNames[state.beach]).filter(record=>record.cause===cause);const card=document.querySelector('.accident');document.querySelector('.incident-detail')?.remove();const detail=document.createElement('div');detail.className='incident-detail';detail.innerHTML=records.map(record=>`<b>${record.date}</b><span>${record.detail||'상세 내용 미입력'}</span>`).join('');card.insertAdjacentElement('afterend',detail);};
  function addManagerButton(){if(document.querySelector('.incident-manager'))return;const header=document.querySelector('.top');if(!header)return;const button=document.createElement('button');button.className='incident-manager';button.textContent='사고 기록 관리';button.onclick=openManager;header.insertAdjacentElement('afterend',button);}
  function openManager(){const today=new Date().toISOString().slice(0,10);document.body.insertAdjacentHTML('beforeend',`<div class="modal" onclick="if(event.target===this)this.remove()"><div class="sheet manager-sheet"><button class="icon-btn close" onclick="this.closest('.modal').remove()">×</button><h2>사고 기록 관리</h2><p>공식 기관 확인 자료만 등록하세요. 이 기기에만 저장됩니다.</p><label>발생일<input id="incident-date" type="date" value="${today}"></label><label>해수욕장<select id="incident-beach">${beachNames.map(name=>`<option>${name}</option>`).join('')}</select></label><label>사고 유형<select id="incident-cause">${causes.map(cause=>`<option>${cause}</option>`).join('')}</select></label><label>공식 확인 내용<textarea id="incident-detail" placeholder="출처와 확인한 사고 내용을 적으세요."></textarea></label><button class="save-incident" onclick="saveIncidentRecord()">공식 확인 기록 등록</button><div class="record-list">${load().slice().reverse().map(record=>`<div><b>${record.date} · ${record.beach}</b><span>${record.cause}</span></div>`).join('')||'<p>아직 등록된 기록이 없습니다.</p>'}</div></div></div>`);}
  window.saveIncidentRecord=function(){const date=document.querySelector('#incident-date').value,beach=document.querySelector('#incident-beach').value,cause=document.querySelector('#incident-cause').value,detail=document.querySelector('#incident-detail').value.trim();if(!date||!detail){alert('발생일과 공식 확인 내용을 입력하세요.');return;}const records=load();records.push({id:Date.now(),date,beach,cause,detail});save(records);document.querySelector('.modal')?.remove();window.render();};
  const style=document.createElement('style');style.textContent=`.incident-manager{margin:0 16px 8px;border:0;background:transparent;color:var(--ocean);font:inherit;font-size:12px;font-weight:700;text-decoration:underline}.empty-incidents{padding:18px 16px;color:var(--muted);font-size:13px}.incident-detail{margin:0 16px;padding:12px 14px;border-radius:0 0 16px 16px;background:#eaf7f6;font-size:12px}.incident-detail b,.incident-detail span{display:block}.incident-detail span{margin:4px 0 10px;color:var(--muted);line-height:1.5}.manager-sheet label{display:block;margin:12px 0;color:var(--ink);font-size:12px;font-weight:700}.manager-sheet input,.manager-sheet select,.manager-sheet textarea{display:block;width:100%;margin-top:6px;padding:11px;border:1px solid var(--line);border-radius:10px;background:var(--surface);color:var(--ink);font:inherit}.manager-sheet textarea{height:76px;resize:vertical}.save-incident{width:100%;margin-top:5px;padding:13px;border:0;border-radius:12px;background:var(--deep);color:#fff;font:inherit;font-weight:700}.record-list{margin-top:17px;border-top:1px solid var(--line);padding-top:10px}.record-list div{padding:8px 0;font-size:12px}.record-list b,.record-list span{display:block}.record-list span{color:var(--muted);margin-top:3px}body.dark .incident-detail{background:#173c44}`;document.head.appendChild(style);
  renderIncidents();addManagerButton();
}());
